// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtdOvBdxCpTwJapGbNnVLRzmdtrZ9-DY8',
    appId: '1:181974127537:web:49c1e0c32db71c716e2390',
    messagingSenderId: '181974127537',
    projectId: 'firewithflutter-42352',
    authDomain: 'firewithflutter-42352.firebaseapp.com',
    storageBucket: 'firewithflutter-42352.firebasestorage.app',
    measurementId: 'G-R48ZGMKDKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGquGfGtFDya39waLyowmkwZxXCj358vw',
    appId: '1:181974127537:android:8218a9016c79baa36e2390',
    messagingSenderId: '181974127537',
    projectId: 'firewithflutter-42352',
    storageBucket: 'firewithflutter-42352.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFqMhJxkPfAC-8RTMLTActakEAqm6KDs',
    appId: '1:181974127537:ios:79a443f5e4e842686e2390',
    messagingSenderId: '181974127537',
    projectId: 'firewithflutter-42352',
    storageBucket: 'firewithflutter-42352.firebasestorage.app',
    androidClientId: '181974127537-aap5hhcgs054jve6ddaroaurc7lt8bs3.apps.googleusercontent.com',
    iosClientId: '181974127537-eh2mu99scd3g18l2fjsvumcn5jth3uvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOFqMhJxkPfAC-8RTMLTActakEAqm6KDs',
    appId: '1:181974127537:ios:79a443f5e4e842686e2390',
    messagingSenderId: '181974127537',
    projectId: 'firewithflutter-42352',
    storageBucket: 'firewithflutter-42352.firebasestorage.app',
    androidClientId: '181974127537-aap5hhcgs054jve6ddaroaurc7lt8bs3.apps.googleusercontent.com',
    iosClientId: '181974127537-eh2mu99scd3g18l2fjsvumcn5jth3uvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtdOvBdxCpTwJapGbNnVLRzmdtrZ9-DY8',
    appId: '1:181974127537:web:33cb1e193f0bc8916e2390',
    messagingSenderId: '181974127537',
    projectId: 'firewithflutter-42352',
    authDomain: 'firewithflutter-42352.firebaseapp.com',
    storageBucket: 'firewithflutter-42352.firebasestorage.app',
    measurementId: 'G-8PCKLTHKLP',
  );

}